AEmitterCameraLensEffectBase = {} ---@type AEmitter
AEmitterCameraLensEffectBase.PS_CameraEffect = nil
AEmitterCameraLensEffectBase.PS_CameraEffectNonExtremeContent_DEPRECATED = nil
AEmitterCameraLensEffectBase.BaseCamera = nil
AEmitterCameraLensEffectBase.RelativeTransform = nil
AEmitterCameraLensEffectBase.BaseFOV = nil
AEmitterCameraLensEffectBase.bAllowMultipleInstances = nil
AEmitterCameraLensEffectBase.bResetWhenRetriggered = nil
AEmitterCameraLensEffectBase.EmittersToTreatAsSame = nil
AEmitterCameraLensEffectBase.DistFromCamera_DEPRECATED = nil
