ALandscapeGizmoActor = {} ---@type AActor
ALandscapeGizmoActor.Width = nil
ALandscapeGizmoActor.Height = nil
ALandscapeGizmoActor.LengthZ = nil
ALandscapeGizmoActor.MarginZ = nil
ALandscapeGizmoActor.MinRelativeZ = nil
ALandscapeGizmoActor.RelativeScaleZ = nil
ALandscapeGizmoActor.TargetLandscapeInfo = nil
ALandscapeGizmoActor.SpriteComponent = nil
