AMatineeActor = {} ---@type AActor
AMatineeActor.MatineeData = nil
AMatineeActor.MatineeControllerName = nil
AMatineeActor.PlayRate = nil
AMatineeActor.bPlayOnLevelLoad = nil
AMatineeActor.bForceStartPos = nil
AMatineeActor.ForceStartPosition = nil
AMatineeActor.bLooping = nil
AMatineeActor.bRewindOnPlay = nil
AMatineeActor.bNoResetOnRewind = nil
AMatineeActor.bRewindIfAlreadyPlaying = nil
AMatineeActor.bDisableRadioFilter = nil
AMatineeActor.bClientSideOnly = nil
AMatineeActor.bSkipUpdateIfNotVisible = nil
AMatineeActor.bIsSkippable = nil
AMatineeActor.PreferredSplitScreenNum = nil
AMatineeActor.bDisableMovementInput = nil
AMatineeActor.bDisableLookAtInput = nil
AMatineeActor.bHidePlayer = nil
AMatineeActor.bHideHud = nil
AMatineeActor.GroupActorInfos = nil
AMatineeActor.bShouldShowGore = nil
AMatineeActor.GroupInst = nil
AMatineeActor.CameraCuts = nil
AMatineeActor.SpriteComponent = nil
AMatineeActor.bIsBeingEdited = nil
AMatineeActor.bIsScrubbing = nil
AMatineeActor.bIsPlaying = nil
AMatineeActor.bReversePlayback = nil
AMatineeActor.bPaused = nil
AMatineeActor.bPendingStop = nil
AMatineeActor.InterpPosition = nil
AMatineeActor.ReplicationForceIsPlaying = nil
AMatineeActor.OnPlay = nil
AMatineeActor.OnStop = nil
AMatineeActor.OnPause = nil
function AMatineeActor.Play() end
function AMatineeActor.Stop() end
function AMatineeActor.Reverse() end
function AMatineeActor.Pause() end
function AMatineeActor.SetPosition(NewPosition) end
function AMatineeActor.ChangePlaybackDirection() end
function AMatineeActor.SetLoopingState(bNewLooping) end
function AMatineeActor.EnableGroupByName(GroupName, bEnable) end
