ANavigationData = {} ---@type AActor
ANavigationData.RenderingComp = nil
ANavigationData.NavDataConfig = nil
ANavigationData.bEnableDrawing = nil
ANavigationData.bForceRebuildOnLoad = nil
ANavigationData.bAutoDestroyWhenNoNavigation = nil
ANavigationData.bCanBeMainNavData = nil
ANavigationData.bCanSpawnOnRebuild = nil
ANavigationData.bRebuildAtRuntime_DEPRECATED = nil
ANavigationData.RuntimeGeneration = nil
ANavigationData.ObservedPathsTickInterval = nil
ANavigationData.DataVersion = nil
ANavigationData.SupportedAreas = nil
