ATransformGizmoActor = {} ---@type AGizmoActor
ATransformGizmoActor.TranslateX = nil
ATransformGizmoActor.TranslateY = nil
ATransformGizmoActor.TranslateZ = nil
ATransformGizmoActor.TranslateYZ = nil
ATransformGizmoActor.TranslateXZ = nil
ATransformGizmoActor.TranslateXY = nil
ATransformGizmoActor.RotateX = nil
ATransformGizmoActor.RotateY = nil
ATransformGizmoActor.RotateZ = nil
