EDefaultBackBufferPixelFormat = {}
EDefaultBackBufferPixelFormat.DBBPF_B8G8R8A8 = nil
EDefaultBackBufferPixelFormat.DBBPF_A16B16G16R16_DEPRECATED = nil
EDefaultBackBufferPixelFormat.DBBPF_FloatRGB_DEPRECATED = nil
EDefaultBackBufferPixelFormat.DBBPF_FloatRGBA = nil
EDefaultBackBufferPixelFormat.DBBPF_A2B10G10R10 = nil
EDefaultBackBufferPixelFormat.DBBPF_MAX = nil
