ELocationBoneSocketSelectionMethod = {}
ELocationBoneSocketSelectionMethod.BONESOCKETSEL_Sequential = nil
ELocationBoneSocketSelectionMethod.BONESOCKETSEL_Random = nil
ELocationBoneSocketSelectionMethod.BONESOCKETSEL_MAX = nil
