ELocationSkelVertSurfaceSource = {}
ELocationSkelVertSurfaceSource.VERTSURFACESOURCE_Vert = nil
ELocationSkelVertSurfaceSource.VERTSURFACESOURCE_Surface = nil
ELocationSkelVertSurfaceSource.VERTSURFACESOURCE_MAX = nil
