EMaterialVectorCoordTransformSource = {}
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_Tangent = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_Local = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_World = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_View = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_Camera = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_ParticleWorld = nil
EMaterialVectorCoordTransformSource.TRANSFORMSOURCE_MAX = nil
