EMaxConcurrentResolutionRule = {}
EMaxConcurrentResolutionRule.PreventNew = nil
EMaxConcurrentResolutionRule.StopOldest = nil
EMaxConcurrentResolutionRule.StopFarthestThenPreventNew = nil
EMaxConcurrentResolutionRule.StopFarthestThenOldest = nil
EMaxConcurrentResolutionRule.StopLowestPriority = nil
EMaxConcurrentResolutionRule.StopQuietest = nil
EMaxConcurrentResolutionRule.StopLowestPriorityThenPreventNew = nil
