EParticleSystemOcclusionBoundsMethod = {}
EParticleSystemOcclusionBoundsMethod.EPSOBM_None = nil
EParticleSystemOcclusionBoundsMethod.EPSOBM_ParticleBounds = nil
EParticleSystemOcclusionBoundsMethod.EPSOBM_CustomBounds = nil
