EParticleSystemInsignificanceReaction = {}
EParticleSystemInsignificanceReaction.Auto = nil
EParticleSystemInsignificanceReaction.Complete = nil
EParticleSystemInsignificanceReaction.DisableTick = nil
EParticleSystemInsignificanceReaction.DisableTickAndKill = nil
EParticleSystemInsignificanceReaction.Num = nil
