ESceneCapturePrimitiveRenderMode = {}
ESceneCapturePrimitiveRenderMode.PRM_LegacySceneCapture = nil
ESceneCapturePrimitiveRenderMode.PRM_RenderScenePrimitives = nil
ESceneCapturePrimitiveRenderMode.PRM_UseShowOnlyList = nil
