EVisibilityBasedAnimTickOption = {}
EVisibilityBasedAnimTickOption.AlwaysTickPoseAndRefreshBones = nil
EVisibilityBasedAnimTickOption.AlwaysTickPose = nil
EVisibilityBasedAnimTickOption.OnlyTickMontagesWhenNotRendered = nil
EVisibilityBasedAnimTickOption.OnlyTickPoseWhenRendered = nil
