FAssetRegistryDependencyOptions = {}
FAssetRegistryDependencyOptions.bIncludeSoftPackageReferences = nil
FAssetRegistryDependencyOptions.bIncludeHardPackageReferences = nil
FAssetRegistryDependencyOptions.bIncludeSearchableNames = nil
FAssetRegistryDependencyOptions.bIncludeSoftManagementReferences = nil
FAssetRegistryDependencyOptions.bIncludeHardManagementReferences = nil
