FAutomationWorkerPerformanceDataRequest = {}
FAutomationWorkerPerformanceDataRequest.Platform = nil
FAutomationWorkerPerformanceDataRequest.Hardware = nil
FAutomationWorkerPerformanceDataRequest.TestName = nil
FAutomationWorkerPerformanceDataRequest.DataPoints = nil
