FBakedStateExitTransition = {}
FBakedStateExitTransition.CanTakeDelegateIndex = nil
FBakedStateExitTransition.CustomResultNodeIndex = nil
FBakedStateExitTransition.TransitionIndex = nil
FBakedStateExitTransition.bDesiredTransitionReturnValue = nil
FBakedStateExitTransition.bAutomaticRemainingTimeRule = nil
FBakedStateExitTransition.PoseEvaluatorLinks = nil
