FBlueprintComponentChangedPropertyInfo = {}
FBlueprintComponentChangedPropertyInfo.PropertyName = nil
FBlueprintComponentChangedPropertyInfo.ArrayIndex = nil
FBlueprintComponentChangedPropertyInfo.PropertyScope = nil
