FBlueprintEditorPromotionSettings = {}
FBlueprintEditorPromotionSettings.FirstMeshPath = nil
FBlueprintEditorPromotionSettings.SecondMeshPath = nil
FBlueprintEditorPromotionSettings.DefaultParticleAsset = nil
