FBlueprintComponentDelegateBinding = {}
FBlueprintComponentDelegateBinding.ComponentPropertyName = nil
FBlueprintComponentDelegateBinding.DelegatePropertyName = nil
FBlueprintComponentDelegateBinding.FunctionNameToBind = nil
