FBlueprintInputActionDelegateBinding = {}
FBlueprintInputActionDelegateBinding.InputActionName = nil
FBlueprintInputActionDelegateBinding.InputKeyEvent = nil
FBlueprintInputActionDelegateBinding.FunctionNameToBind = nil
