FEditorImportExportTestDefinition = {}
FEditorImportExportTestDefinition.ImportFilePath = nil
FEditorImportExportTestDefinition.ExportFileExtension = nil
FEditorImportExportTestDefinition.bSkipExport = nil
FEditorImportExportTestDefinition.FactorySettings = nil
