FForeignWorldSplineData = {}
FForeignWorldSplineData.ForeignControlPointDataMap_DEPRECATED = nil
FForeignWorldSplineData.ForeignControlPointData = nil
FForeignWorldSplineData.ForeignSplineSegmentDataMap_DEPRECATED = nil
FForeignWorldSplineData.ForeignSplineSegmentData = nil
