FGeometryCollectionDebugDrawActorSelectedRigidBody = {}
FGeometryCollectionDebugDrawActorSelectedRigidBody.Id = nil
FGeometryCollectionDebugDrawActorSelectedRigidBody.Solver = nil
FGeometryCollectionDebugDrawActorSelectedRigidBody.GeometryCollection = nil
