FMaterialEditorPromotionSettings = {}
FMaterialEditorPromotionSettings.DefaultMaterialAsset = nil
FMaterialEditorPromotionSettings.DefaultDiffuseTexture = nil
FMaterialEditorPromotionSettings.DefaultNormalTexture = nil
