FMovieSceneCameraCutSectionTemplate = {}
FMovieSceneCameraCutSectionTemplate.CameraBindingID = nil
FMovieSceneCameraCutSectionTemplate.CutTransform = nil
FMovieSceneCameraCutSectionTemplate.bHasCutTransform = nil
