FMovieSceneTemplateGenerationLedger = {}
FMovieSceneTemplateGenerationLedger.LastTrackIdentifier = nil
FMovieSceneTemplateGenerationLedger.TrackSignatureToTrackIdentifier = nil
FMovieSceneTemplateGenerationLedger.SubSectionRanges = nil
