FMovieSceneSkeletalAnimationSectionTemplateParameters = {}
FMovieSceneSkeletalAnimationSectionTemplateParameters.SectionStartTime = nil
FMovieSceneSkeletalAnimationSectionTemplateParameters.SectionEndTime = nil
