FMovieSceneSequenceReplProperties = {}
FMovieSceneSequenceReplProperties.LastKnownPosition = nil
FMovieSceneSequenceReplProperties.LastKnownStatus = nil
FMovieSceneSequenceReplProperties.LastKnownNumLoops = nil
