FPortalPackageInstallerInstallRequest = {}
FPortalPackageInstallerInstallRequest.AppName = nil
FPortalPackageInstallerInstallRequest.BuildLabel = nil
FPortalPackageInstallerInstallRequest.DestinationPath = nil
