FRuntimeVirtualTextureParameterValue = {}
FRuntimeVirtualTextureParameterValue.ParameterInfo = nil
FRuntimeVirtualTextureParameterValue.ParameterValue = nil
FRuntimeVirtualTextureParameterValue.ExpressionGUID = nil
