FSkeletalMeshSamplingRegionBoneFilter = {}
FSkeletalMeshSamplingRegionBoneFilter.BoneName = nil
FSkeletalMeshSamplingRegionBoneFilter.bIncludeOrExclude = nil
FSkeletalMeshSamplingRegionBoneFilter.bApplyToChildren = nil
