FSoundAttenuationPluginSettings = {}
FSoundAttenuationPluginSettings.SpatializationPluginSettingsArray = nil
FSoundAttenuationPluginSettings.OcclusionPluginSettingsArray = nil
FSoundAttenuationPluginSettings.ReverbPluginSettingsArray = nil
