FStaticMeshComponentInstanceData = {}
FStaticMeshComponentInstanceData.StaticMesh = nil
FStaticMeshComponentInstanceData.VertexColorLODs = nil
FStaticMeshComponentInstanceData.CachedStaticLighting = nil
FStaticMeshComponentInstanceData.StreamingTextureData = nil
FStaticMeshComponentInstanceData.MaterialStreamingRelativeBoxes = nil
