FWidgetCarouselNavigationButtonStyle = {}
FWidgetCarouselNavigationButtonStyle.InnerButtonStyle = nil
FWidgetCarouselNavigationButtonStyle.NavigationButtonLeftImage = nil
FWidgetCarouselNavigationButtonStyle.NavigationButtonRightImage = nil
