FWidgetCarouselNavigationBarStyle = {}
FWidgetCarouselNavigationBarStyle.HighlightBrush = nil
FWidgetCarouselNavigationBarStyle.LeftButtonStyle = nil
FWidgetCarouselNavigationBarStyle.CenterButtonStyle = nil
FWidgetCarouselNavigationBarStyle.RightButtonStyle = nil
