ParticleSystemLODMethod = {}
ParticleSystemLODMethod.PARTICLESYSTEMLODMETHOD_Automatic = nil
ParticleSystemLODMethod.PARTICLESYSTEMLODMETHOD_DirectSet = nil
ParticleSystemLODMethod.PARTICLESYSTEMLODMETHOD_ActivateAutomatic = nil
