SkeletalMeshTerminationCriterion = {}
SkeletalMeshTerminationCriterion.SMTC_NumOfTriangles = nil
SkeletalMeshTerminationCriterion.SMTC_NumOfVerts = nil
SkeletalMeshTerminationCriterion.SMTC_TriangleOrVert = nil
SkeletalMeshTerminationCriterion.SMTC_AbsNumOfTriangles = nil
SkeletalMeshTerminationCriterion.SMTC_AbsNumOfVerts = nil
SkeletalMeshTerminationCriterion.SMTC_AbsTriangleOrVert = nil
SkeletalMeshTerminationCriterion.SMTC_MAX = nil
