UActorComponent = {} ---@type UObject
UActorComponent.PrimaryComponentTick = nil
UActorComponent.ComponentTags = nil
UActorComponent.AssetUserData = nil
UActorComponent.bReplicates = nil
UActorComponent.bNetAddressable = nil
UActorComponent.bCreatedByConstructionScript_DEPRECATED = nil
UActorComponent.bInstanceComponent_DEPRECATED = nil
UActorComponent.bAutoActivate = nil
UActorComponent.bIsActive = nil
UActorComponent.bEditableWhenInherited = nil
UActorComponent.bCanEverAffectNavigation = nil
UActorComponent.bIsEditorOnly = nil
UActorComponent.bIsVisualizationComponent = nil
UActorComponent.CreationMethod = nil
UActorComponent.OnComponentActivated = nil
UActorComponent.OnComponentDeactivated = nil
UActorComponent.UCSModifiedProperties = nil
function UActorComponent.IsBeingDestroyed() end
function UActorComponent.OnRep_IsActive() end
function UActorComponent.GetOwner() end
function UActorComponent.ComponentHasTag(Tag) end
function UActorComponent.Activate() end
function UActorComponent.Deactivate() end
function UActorComponent.SetActive(bNewActive) end
function UActorComponent.ToggleActive() end
function UActorComponent.IsActive() end
function UActorComponent.SetAutoActivate(bNewAutoActivate) end
function UActorComponent.SetTickableWhenPaused(bTickableWhenPaused) end
function UActorComponent.SetIsReplicated(ShouldReplicate) end
function UActorComponent.ReceiveBeginPlay() end
function UActorComponent.ReceiveEndPlay(EndPlayReason) end
function UActorComponent.SetComponentTickEnabled(bEnabled) end
function UActorComponent.IsComponentTickEnabled() end
function UActorComponent.SetComponentTickInterval(TickInterval) end
function UActorComponent.GetComponentTickInterval() end
function UActorComponent.K2_DestroyComponent(Object) end
function UActorComponent.SetTickGroup(NewTickGroup) end
function UActorComponent.AddTickPrerequisiteActor(PrerequisiteActor) end
function UActorComponent.AddTickPrerequisiteComponent(PrerequisiteComponent) end
function UActorComponent.RemoveTickPrerequisiteActor(PrerequisiteActor) end
function UActorComponent.RemoveTickPrerequisiteComponent(PrerequisiteComponent) end
function UActorComponent.ReceiveTick(DeltaSeconds) end
