UAnimationSettings = {} ---@type UDeveloperSettings
UAnimationSettings.CompressCommandletVersion = nil
UAnimationSettings.KeyEndEffectorsMatchNameArray = nil
UAnimationSettings.DefaultCompressionAlgorithm = nil
UAnimationSettings.RotationCompressionFormat = nil
UAnimationSettings.TranslationCompressionFormat = nil
UAnimationSettings.MaxCurveError = nil
UAnimationSettings.AlternativeCompressionThreshold = nil
UAnimationSettings.ForceRecompression = nil
UAnimationSettings.bOnlyCheckForMissingSkeletalMeshes = nil
UAnimationSettings.bForceBelowThreshold = nil
UAnimationSettings.bFirstRecompressUsingCurrentOrDefault = nil
UAnimationSettings.bRaiseMaxErrorToExisting = nil
UAnimationSettings.bTryExhaustiveSearch = nil
UAnimationSettings.bEnableSegmenting = nil
UAnimationSettings.bEnablePerformanceLog = nil
UAnimationSettings.bStripAnimationDataOnDedicatedServer = nil
UAnimationSettings.bTickAnimationOnSkeletalMeshInit = nil
