UAnimSet = {} ---@type UObject
UAnimSet.bAnimRotationOnly = nil
UAnimSet.TrackBoneNames = nil
UAnimSet.Sequences = nil
UAnimSet.LinkupCache = nil
UAnimSet.BoneUseAnimTranslation = nil
UAnimSet.ForceUseMeshTranslation = nil
UAnimSet.UseTranslationBoneNames = nil
UAnimSet.ForceMeshTranslationBoneNames = nil
UAnimSet.PreviewSkelMeshName = nil
UAnimSet.BestRatioSkelMeshName = nil
