UAnimCompress_RemoveLinearKeys = {} ---@type UAnimCompress
UAnimCompress_RemoveLinearKeys.MaxPosDiff = nil
UAnimCompress_RemoveLinearKeys.MaxAngleDiff = nil
UAnimCompress_RemoveLinearKeys.MaxScaleDiff = nil
UAnimCompress_RemoveLinearKeys.MaxEffectorDiff = nil
UAnimCompress_RemoveLinearKeys.MinEffectorDiff = nil
UAnimCompress_RemoveLinearKeys.EffectorDiffSocket = nil
UAnimCompress_RemoveLinearKeys.ParentKeyScale = nil
UAnimCompress_RemoveLinearKeys.bRetarget = nil
UAnimCompress_RemoveLinearKeys.bActuallyFilterLinearKeys = nil
UAnimCompress_RemoveLinearKeys.bOptimizeForForwardPlayback = nil
UAnimCompress_RemoveLinearKeys.bUseDecompression = nil
UAnimCompress_RemoveLinearKeys.bUseMultithreading = nil
