UARGetCandidateObjectAsyncTaskBlueprintProxy = {} ---@type UARBaseAsyncTaskBlueprintProxy
UARGetCandidateObjectAsyncTaskBlueprintProxy.OnSuccess = nil
UARGetCandidateObjectAsyncTaskBlueprintProxy.OnFailed = nil
function UARGetCandidateObjectAsyncTaskBlueprintProxy.ARGetCandidateObject(WorldContextObject, Location, Extent) end
