UARSessionConfig = {} ---@type UDataAsset
UARSessionConfig.bGenerateMeshDataFromTrackedGeometry = nil
UARSessionConfig.bGenerateCollisionForMeshData = nil
UARSessionConfig.bGenerateNavMeshForMeshData = nil
UARSessionConfig.bUseMeshDataForOcclusion = nil
UARSessionConfig.bRenderMeshDataInWireframe = nil
UARSessionConfig.bTrackSceneObjects = nil
UARSessionConfig.bUsePersonSegmentationForOcclusion = nil
UARSessionConfig.WorldAlignment = nil
UARSessionConfig.SessionType = nil
UARSessionConfig.PlaneDetectionMode_DEPRECATED = nil
UARSessionConfig.bHorizontalPlaneDetection = nil
UARSessionConfig.bVerticalPlaneDetection = nil
UARSessionConfig.bEnableAutoFocus = nil
UARSessionConfig.LightEstimationMode = nil
UARSessionConfig.FrameSyncMode = nil
UARSessionConfig.bEnableAutomaticCameraOverlay = nil
UARSessionConfig.bEnableAutomaticCameraTracking = nil
UARSessionConfig.bResetCameraTracking = nil
UARSessionConfig.bResetTrackedObjects = nil
UARSessionConfig.CandidateImages = nil
UARSessionConfig.MaxNumSimultaneousImagesTracked = nil
UARSessionConfig.EnvironmentCaptureProbeType = nil
UARSessionConfig.WorldMapData = nil
UARSessionConfig.CandidateObjects = nil
UARSessionConfig.DesiredVideoFormat = nil
UARSessionConfig.FaceTrackingDirection = nil
UARSessionConfig.FaceTrackingUpdate = nil
UARSessionConfig.SerializedARCandidateImageDatabase = nil
UARSessionConfig.EnabledSessionTrackingFeature = nil
function UARSessionConfig.GetWorldAlignment() end
function UARSessionConfig.GetSessionType() end
function UARSessionConfig.GetPlaneDetectionMode() end
function UARSessionConfig.GetLightEstimationMode() end
function UARSessionConfig.GetFrameSyncMode() end
function UARSessionConfig.ShouldRenderCameraOverlay() end
function UARSessionConfig.ShouldEnableCameraTracking() end
function UARSessionConfig.ShouldEnableAutoFocus() end
function UARSessionConfig.SetEnableAutoFocus(bNewValue) end
function UARSessionConfig.ShouldResetCameraTracking() end
function UARSessionConfig.SetResetCameraTracking(bNewValue) end
function UARSessionConfig.ShouldResetTrackedObjects() end
function UARSessionConfig.SetResetTrackedObjects(bNewValue) end
function UARSessionConfig.GetCandidateImageList() end
function UARSessionConfig.AddCandidateImage(NewCandidateImage) end
function UARSessionConfig.GetMaxNumSimultaneousImagesTracked() end
function UARSessionConfig.GetEnvironmentCaptureProbeType() end
function UARSessionConfig.GetWorldMapData() end
function UARSessionConfig.SetWorldMapData(WorldMapData) end
function UARSessionConfig.GetCandidateObjectList() end
function UARSessionConfig.SetCandidateObjectList(InCandidateObjects) end
function UARSessionConfig.AddCandidateObject(CandidateObject) end
function UARSessionConfig.GetDesiredVideoFormat() end
function UARSessionConfig.SetDesiredVideoFormat(NewFormat) end
function UARSessionConfig.GetFaceTrackingDirection() end
function UARSessionConfig.SetFaceTrackingDirection(InDirection) end
function UARSessionConfig.GetFaceTrackingUpdate() end
function UARSessionConfig.SetFaceTrackingUpdate(InUpdate) end
function UARSessionConfig.GetEnabledSessionTrackingFeature() end
function UARSessionConfig.SetSessionTrackingFeatureToEnable(InSessionTrackingFeature) end
