UAssetManagerSettings = {} ---@type UDeveloperSettings
UAssetManagerSettings.PrimaryAssetTypesToScan = nil
UAssetManagerSettings.DirectoriesToExclude = nil
UAssetManagerSettings.PrimaryAssetRules = nil
UAssetManagerSettings.CustomPrimaryAssetRules = nil
UAssetManagerSettings.bOnlyCookProductionAssets = nil
UAssetManagerSettings.bShouldManagerDetermineTypeAndName = nil
UAssetManagerSettings.bShouldGuessTypeAndNameInEditor = nil
UAssetManagerSettings.bShouldAcquireMissingChunksOnLoad = nil
UAssetManagerSettings.PrimaryAssetIdRedirects = nil
UAssetManagerSettings.PrimaryAssetTypeRedirects = nil
UAssetManagerSettings.AssetPathRedirects = nil
UAssetManagerSettings.MetaDataTagsForAssetRegistry = nil
