UBlueprintGeneratedClass = {} ---@type UClass
UBlueprintGeneratedClass.NumReplicatedProperties = nil
UBlueprintGeneratedClass.bHasNativizedParent = nil
UBlueprintGeneratedClass.bHasCookedComponentInstancingData = nil
UBlueprintGeneratedClass.bIsSparseClassDataSerializable = nil
UBlueprintGeneratedClass.DynamicBindingObjects = nil
UBlueprintGeneratedClass.ComponentTemplates = nil
UBlueprintGeneratedClass.Timelines = nil
UBlueprintGeneratedClass.ComponentClassOverrides = nil
UBlueprintGeneratedClass.SimpleConstructionScript = nil
UBlueprintGeneratedClass.InheritableComponentHandler = nil
UBlueprintGeneratedClass.UberGraphFramePointerProperty = nil
UBlueprintGeneratedClass.UberGraphFunction = nil
UBlueprintGeneratedClass.FastCallPairs_DEPRECATED = nil
UBlueprintGeneratedClass.OverridenArchetypeForCDO = nil
UBlueprintGeneratedClass.PropertyGuids = nil
UBlueprintGeneratedClass.CalledFunctions = nil
UBlueprintGeneratedClass.CookedComponentInstancingData = nil
