UBodySetup = {} ---@type UObject
UBodySetup.AggGeom = nil
UBodySetup.BoneName = nil
UBodySetup.PhysicsType = nil
UBodySetup.bAlwaysFullAnimWeight_DEPRECATED = nil
UBodySetup.bConsiderForBounds = nil
UBodySetup.bMeshCollideAll = nil
UBodySetup.bDoubleSidedGeometry = nil
UBodySetup.bGenerateNonMirroredCollision = nil
UBodySetup.bSharedCookedData = nil
UBodySetup.bGenerateMirroredCollision = nil
UBodySetup.CollisionReponse = nil
UBodySetup.CollisionTraceFlag = nil
UBodySetup.PhysMaterial = nil
UBodySetup.WalkableSlopeOverride = nil
UBodySetup.BuildScale_DEPRECATED = nil
UBodySetup.DefaultInstance = nil
UBodySetup.BuildScale3D = nil
