UBorder = {} ---@type UContentWidget
UBorder.HorizontalAlignment = nil
UBorder.VerticalAlignment = nil
UBorder.bShowEffectWhenDisabled = nil
UBorder.ContentColorAndOpacity = nil
UBorder.ContentColorAndOpacityDelegate = nil
UBorder.Padding = nil
UBorder.Background = nil
UBorder.BackgroundDelegate = nil
UBorder.BrushColor = nil
UBorder.BrushColorDelegate = nil
UBorder.DesiredSizeScale = nil
UBorder.bFlipForRightToLeftFlowDirection = nil
UBorder.OnMouseButtonDownEvent = nil
UBorder.OnMouseButtonUpEvent = nil
UBorder.OnMouseMoveEvent = nil
UBorder.OnMouseDoubleClickEvent = nil
UBorder.Brush_DEPRECATED = nil
function UBorder.SetContentColorAndOpacity(InContentColorAndOpacity) end
function UBorder.SetPadding(InPadding) end
function UBorder.SetHorizontalAlignment(InHorizontalAlignment) end
function UBorder.SetVerticalAlignment(InVerticalAlignment) end
function UBorder.SetBrushColor(InBrushColor) end
function UBorder.SetBrush(InBrush) end
function UBorder.SetBrushFromAsset(Asset) end
function UBorder.SetBrushFromTexture(Texture) end
function UBorder.SetBrushFromMaterial(Material) end
function UBorder.GetDynamicMaterial() end
function UBorder.SetDesiredSizeScale(InScale) end
