UBTTask_MoveTo = {} ---@type UBTTask_BlackboardBase
UBTTask_MoveTo.AcceptableRadius = nil
UBTTask_MoveTo.FilterClass = nil
UBTTask_MoveTo.ObservedBlackboardValueTolerance = nil
UBTTask_MoveTo.bObserveBlackboardValue = nil
UBTTask_MoveTo.bAllowStrafe = nil
UBTTask_MoveTo.bAllowPartialPath = nil
UBTTask_MoveTo.bTrackMovingGoal = nil
UBTTask_MoveTo.bProjectGoalLocation = nil
UBTTask_MoveTo.bReachTestIncludesAgentRadius = nil
UBTTask_MoveTo.bReachTestIncludesGoalRadius = nil
UBTTask_MoveTo.bStopOnOverlap = nil
UBTTask_MoveTo.bStopOnOverlapNeedsUpdate = nil
