UComboBoxString = {} ---@type UWidget
UComboBoxString.DefaultOptions = nil
UComboBoxString.SelectedOption = nil
UComboBoxString.WidgetStyle = nil
UComboBoxString.ItemStyle = nil
UComboBoxString.ContentPadding = nil
UComboBoxString.MaxListHeight = nil
UComboBoxString.HasDownArrow = nil
UComboBoxString.EnableGamepadNavigationMode = nil
UComboBoxString.Font = nil
UComboBoxString.ForegroundColor = nil
UComboBoxString.bIsFocusable = nil
UComboBoxString.OnGenerateWidgetEvent = nil
UComboBoxString.OnSelectionChanged = nil
UComboBoxString.OnOpening = nil
function UComboBoxString.AddOption(Option) end
function UComboBoxString.RemoveOption(Option) end
function UComboBoxString.FindOptionIndex(Option) end
function UComboBoxString.GetOptionAtIndex(Index) end
function UComboBoxString.ClearOptions() end
function UComboBoxString.ClearSelection() end
function UComboBoxString.RefreshOptions() end
function UComboBoxString.SetSelectedOption(Option) end
function UComboBoxString.SetSelectedIndex(Index) end
function UComboBoxString.GetSelectedOption() end
function UComboBoxString.GetSelectedIndex() end
function UComboBoxString.GetOptionCount() end
function UComboBoxString.IsOpen() end
