UConsoleSettings = {} ---@type UObject
UConsoleSettings.MaxScrollbackSize = nil
UConsoleSettings.ManualAutoCompleteList = nil
UConsoleSettings.AutoCompleteMapPaths = nil
UConsoleSettings.BackgroundOpacityPercentage = nil
UConsoleSettings.bOrderTopToBottom = nil
UConsoleSettings.bDisplayHelpInAutoComplete = nil
UConsoleSettings.InputColor = nil
UConsoleSettings.HistoryColor = nil
UConsoleSettings.AutoCompleteCommandColor = nil
UConsoleSettings.AutoCompleteCVarColor = nil
UConsoleSettings.AutoCompleteFadedColor = nil
