UEditableTextBox = {} ---@type UWidget
UEditableTextBox.Text = nil
UEditableTextBox.TextDelegate = nil
UEditableTextBox.WidgetStyle = nil
UEditableTextBox.Style_DEPRECATED = nil
UEditableTextBox.HintText = nil
UEditableTextBox.HintTextDelegate = nil
UEditableTextBox.Font_DEPRECATED = nil
UEditableTextBox.ForegroundColor_DEPRECATED = nil
UEditableTextBox.BackgroundColor_DEPRECATED = nil
UEditableTextBox.ReadOnlyForegroundColor_DEPRECATED = nil
UEditableTextBox.IsReadOnly = nil
UEditableTextBox.IsPassword = nil
UEditableTextBox.MinimumDesiredWidth = nil
UEditableTextBox.Padding_DEPRECATED = nil
UEditableTextBox.IsCaretMovedWhenGainFocus = nil
UEditableTextBox.SelectAllTextWhenFocused = nil
UEditableTextBox.RevertTextOnEscape = nil
UEditableTextBox.ClearKeyboardFocusOnCommit = nil
UEditableTextBox.SelectAllTextOnCommit = nil
UEditableTextBox.AllowContextMenu = nil
UEditableTextBox.KeyboardType = nil
UEditableTextBox.VirtualKeyboardOptions = nil
UEditableTextBox.VirtualKeyboardDismissAction = nil
UEditableTextBox.Justification = nil
UEditableTextBox.ShapedTextOptions = nil
UEditableTextBox.OnTextChanged = nil
UEditableTextBox.OnTextCommitted = nil
function UEditableTextBox.GetText() end
function UEditableTextBox.SetText(InText) end
function UEditableTextBox.SetHintText(InText) end
function UEditableTextBox.SetError(InError) end
function UEditableTextBox.SetIsReadOnly(bReadOnly) end
function UEditableTextBox.SetIsPassword(bIsPassword) end
function UEditableTextBox.ClearError() end
function UEditableTextBox.HasError() end
function UEditableTextBox.SetJustification(InJustification) end
