UEngineMessage = {} ---@type ULocalMessage
UEngineMessage.FailedPlaceMessage = nil
UEngineMessage.MaxedOutMessage = nil
UEngineMessage.EnteredMessage = nil
UEngineMessage.LeftMessage = nil
UEngineMessage.GlobalNameChange = nil
UEngineMessage.SpecEnteredMessage = nil
UEngineMessage.NewPlayerMessage = nil
UEngineMessage.NewSpecMessage = nil
