UFieldSystemMetaDataProcessingResolution = {} ---@type UFieldSystemMetaData
UFieldSystemMetaDataProcessingResolution.ResolutionType = nil
function UFieldSystemMetaDataProcessingResolution.SetMetaDataaProcessingResolutionType(ResolutionType) end
