UFoliageInstancedStaticMeshComponent = {} ---@type UHierarchicalInstancedStaticMeshComponent
UFoliageInstancedStaticMeshComponent.OnInstanceTakePointDamage = nil
UFoliageInstancedStaticMeshComponent.OnInstanceTakeRadialDamage = nil
UFoliageInstancedStaticMeshComponent.FoliageHiddenEditorViews = nil
