UGameUserSettings = {} ---@type UObject
UGameUserSettings.bUseVSync = nil
UGameUserSettings.bUseDynamicResolution = nil
UGameUserSettings.ResolutionSizeX = nil
UGameUserSettings.ResolutionSizeY = nil
UGameUserSettings.LastUserConfirmedResolutionSizeX = nil
UGameUserSettings.LastUserConfirmedResolutionSizeY = nil
UGameUserSettings.WindowPosX = nil
UGameUserSettings.WindowPosY = nil
UGameUserSettings.FullscreenMode = nil
UGameUserSettings.LastConfirmedFullscreenMode = nil
UGameUserSettings.PreferredFullscreenMode = nil
UGameUserSettings.Version = nil
UGameUserSettings.AudioQualityLevel = nil
UGameUserSettings.LastConfirmedAudioQualityLevel = nil
UGameUserSettings.FrameRateLimit = nil
UGameUserSettings.DesiredScreenWidth = nil
UGameUserSettings.bUseDesiredScreenHeight = nil
UGameUserSettings.DesiredScreenHeight = nil
UGameUserSettings.LastUserConfirmedDesiredScreenWidth = nil
UGameUserSettings.LastUserConfirmedDesiredScreenHeight = nil
UGameUserSettings.LastRecommendedScreenWidth = nil
UGameUserSettings.LastRecommendedScreenHeight = nil
UGameUserSettings.LastCPUBenchmarkResult = nil
UGameUserSettings.LastGPUBenchmarkResult = nil
UGameUserSettings.LastCPUBenchmarkSteps = nil
UGameUserSettings.LastGPUBenchmarkSteps = nil
UGameUserSettings.LastGPUBenchmarkMultiplier = nil
UGameUserSettings.bUseHDRDisplayOutput = nil
UGameUserSettings.HDRDisplayOutputNits = nil
UGameUserSettings.OnGameUserSettingsUINeedsUpdate = nil
function UGameUserSettings.ApplySettings(bCheckForCommandLineOverrides) end
function UGameUserSettings.ApplyNonResolutionSettings() end
function UGameUserSettings.ApplyResolutionSettings(bCheckForCommandLineOverrides) end
function UGameUserSettings.GetScreenResolution() end
function UGameUserSettings.GetLastConfirmedScreenResolution() end
function UGameUserSettings.GetDesktopResolution() end
function UGameUserSettings.SetScreenResolution(Resolution) end
function UGameUserSettings.GetFullscreenMode() end
function UGameUserSettings.GetLastConfirmedFullscreenMode() end
function UGameUserSettings.SetFullscreenMode(InFullscreenMode) end
function UGameUserSettings.GetPreferredFullscreenMode() end
function UGameUserSettings.SetVSyncEnabled(bEnable) end
function UGameUserSettings.IsVSyncEnabled() end
function UGameUserSettings.SetDynamicResolutionEnabled(bEnable) end
function UGameUserSettings.IsDynamicResolutionEnabled() end
function UGameUserSettings.IsScreenResolutionDirty() end
function UGameUserSettings.IsFullscreenModeDirty() end
function UGameUserSettings.IsVSyncDirty() end
function UGameUserSettings.IsDynamicResolutionDirty() end
function UGameUserSettings.ConfirmVideoMode() end
function UGameUserSettings.RevertVideoMode() end
function UGameUserSettings.SetBenchmarkFallbackValues() end
function UGameUserSettings.SetAudioQualityLevel(QualityLevel) end
function UGameUserSettings.GetAudioQualityLevel() end
function UGameUserSettings.SetFrameRateLimit(NewLimit) end
function UGameUserSettings.GetFrameRateLimit() end
function UGameUserSettings.SetOverallScalabilityLevel(Value) end
function UGameUserSettings.GetOverallScalabilityLevel() end
function UGameUserSettings.GetResolutionScaleInformation(CurrentScaleNormalized, CurrentScaleValue, MinScaleValue, MaxScaleValue) end
function UGameUserSettings.GetResolutionScaleInformationEx(CurrentScaleNormalized, CurrentScaleValue, MinScaleValue, MaxScaleValue) end
function UGameUserSettings.GetResolutionScaleNormalized() end
function UGameUserSettings.SetResolutionScaleValue(NewScaleValue) end
function UGameUserSettings.SetResolutionScaleValueEx(NewScaleValue) end
function UGameUserSettings.SetResolutionScaleNormalized(NewScaleNormalized) end
function UGameUserSettings.SetViewDistanceQuality(Value) end
function UGameUserSettings.GetViewDistanceQuality() end
function UGameUserSettings.SetShadowQuality(Value) end
function UGameUserSettings.GetShadowQuality() end
function UGameUserSettings.SetAntiAliasingQuality(Value) end
function UGameUserSettings.GetAntiAliasingQuality() end
function UGameUserSettings.SetTextureQuality(Value) end
function UGameUserSettings.GetTextureQuality() end
function UGameUserSettings.SetVisualEffectQuality(Value) end
function UGameUserSettings.GetVisualEffectQuality() end
function UGameUserSettings.SetPostProcessingQuality(Value) end
function UGameUserSettings.GetPostProcessingQuality() end
function UGameUserSettings.SetFoliageQuality(Value) end
function UGameUserSettings.GetFoliageQuality() end
function UGameUserSettings.SetShadingQuality(Value) end
function UGameUserSettings.GetShadingQuality() end
function UGameUserSettings.IsDirty() end
function UGameUserSettings.ValidateSettings() end
function UGameUserSettings.LoadSettings() end
function UGameUserSettings.SaveSettings() end
function UGameUserSettings.ResetToCurrentSettings() end
function UGameUserSettings.SetToDefaults() end
function UGameUserSettings.GetDefaultResolutionScale() end
function UGameUserSettings.GetRecommendedResolutionScale() end
function UGameUserSettings.GetDefaultResolution() end
function UGameUserSettings.GetDefaultWindowPosition() end
function UGameUserSettings.GetDefaultWindowMode() end
function UGameUserSettings.GetSyncInterval() end
function UGameUserSettings.GetGameUserSettings() end
function UGameUserSettings.RunHardwareBenchmark() end
function UGameUserSettings.ApplyHardwareBenchmarkResults() end
function UGameUserSettings.SupportsHDRDisplayOutput() end
function UGameUserSettings.EnableHDRDisplayOutput(bEnable) end
function UGameUserSettings.GetCurrentHDRDisplayNits() end
function UGameUserSettings.IsHDREnabled() end
