UGameNetworkManagerSettings = {} ---@type UObject
UGameNetworkManagerSettings.MinDynamicBandwidth = nil
UGameNetworkManagerSettings.MaxDynamicBandwidth = nil
UGameNetworkManagerSettings.TotalNetBandwidth = nil
UGameNetworkManagerSettings.BadPingThreshold = nil
UGameNetworkManagerSettings.bIsStandbyCheckingEnabled = nil
UGameNetworkManagerSettings.StandbyRxCheatTime = nil
UGameNetworkManagerSettings.StandbyTxCheatTime = nil
UGameNetworkManagerSettings.PercentMissingForRxStandby = nil
UGameNetworkManagerSettings.PercentMissingForTxStandby = nil
UGameNetworkManagerSettings.PercentForBadPing = nil
UGameNetworkManagerSettings.JoinInProgressStandbyWaitTime = nil
