UGeometryCollectionDebugDrawComponent = {} ---@type UActorComponent
UGeometryCollectionDebugDrawComponent.GeometryCollectionDebugDrawActor = nil
UGeometryCollectionDebugDrawComponent.GeometryCollectionRenderLevelSetActor = nil
