UInterpGroup = {} ---@type UObject
UInterpGroup.InterpTracks = nil
UInterpGroup.GroupName = nil
UInterpGroup.GroupColor = nil
UInterpGroup.bCollapsed = nil
UInterpGroup.bVisible = nil
UInterpGroup.bIsFolder = nil
UInterpGroup.bIsParented = nil
UInterpGroup.bIsSelected = nil
