UKismetInputLibrary = {} ---@type UBlueprintFunctionLibrary
function UKismetInputLibrary.CalibrateTilt() end
function UKismetInputLibrary.EqualEqual_KeyKey(A, B) end
function UKismetInputLibrary.EqualEqual_InputChordInputChord(A, B) end
function UKismetInputLibrary.Key_IsModifierKey(Key) end
function UKismetInputLibrary.Key_IsGamepadKey(Key) end
function UKismetInputLibrary.Key_IsMouseButton(Key) end
function UKismetInputLibrary.Key_IsKeyboardKey(Key) end
function UKismetInputLibrary.Key_IsFloatAxis(Key) end
function UKismetInputLibrary.Key_IsVectorAxis(Key) end
function UKismetInputLibrary.Key_IsValid(Key) end
function UKismetInputLibrary.Key_GetNavigationAction(InKey) end
function UKismetInputLibrary.Key_GetNavigationActionFromKey(InKeyEvent) end
function UKismetInputLibrary.Key_GetNavigationDirectionFromKey(InKeyEvent) end
function UKismetInputLibrary.Key_GetNavigationDirectionFromAnalog(InAnalogEvent) end
function UKismetInputLibrary.Key_GetDisplayName(Key) end
function UKismetInputLibrary.InputEvent_IsRepeat(Input) end
function UKismetInputLibrary.InputEvent_IsShiftDown(Input) end
function UKismetInputLibrary.InputEvent_IsLeftShiftDown(Input) end
function UKismetInputLibrary.InputEvent_IsRightShiftDown(Input) end
function UKismetInputLibrary.InputEvent_IsControlDown(Input) end
function UKismetInputLibrary.InputEvent_IsLeftControlDown(Input) end
function UKismetInputLibrary.InputEvent_IsRightControlDown(Input) end
function UKismetInputLibrary.InputEvent_IsAltDown(Input) end
function UKismetInputLibrary.InputEvent_IsLeftAltDown(Input) end
function UKismetInputLibrary.InputEvent_IsRightAltDown(Input) end
function UKismetInputLibrary.InputEvent_IsCommandDown(Input) end
function UKismetInputLibrary.InputEvent_IsLeftCommandDown(Input) end
function UKismetInputLibrary.InputEvent_IsRightCommandDown(Input) end
function UKismetInputLibrary.InputChord_GetDisplayName(Key) end
function UKismetInputLibrary.GetKey(Input) end
function UKismetInputLibrary.GetUserIndex(Input) end
function UKismetInputLibrary.GetAnalogValue(Input) end
function UKismetInputLibrary.PointerEvent_GetScreenSpacePosition(Input) end
function UKismetInputLibrary.PointerEvent_GetLastScreenSpacePosition(Input) end
function UKismetInputLibrary.PointerEvent_GetCursorDelta(Input) end
function UKismetInputLibrary.PointerEvent_IsMouseButtonDown(Input, MouseButton) end
function UKismetInputLibrary.PointerEvent_GetEffectingButton(Input) end
function UKismetInputLibrary.PointerEvent_GetWheelDelta(Input) end
function UKismetInputLibrary.PointerEvent_GetUserIndex(Input) end
function UKismetInputLibrary.PointerEvent_GetPointerIndex(Input) end
function UKismetInputLibrary.PointerEvent_GetTouchpadIndex(Input) end
function UKismetInputLibrary.PointerEvent_IsTouchEvent(Input) end
function UKismetInputLibrary.PointerEvent_GetGestureType(Input) end
function UKismetInputLibrary.PointerEvent_GetGestureDelta(Input) end
