ULandscapeInfo = {} ---@type UObject
ULandscapeInfo.LandscapeActor = nil
ULandscapeInfo.LandscapeGuid = nil
ULandscapeInfo.ComponentSizeQuads = nil
ULandscapeInfo.SubsectionSizeQuads = nil
ULandscapeInfo.ComponentNumSubsections = nil
ULandscapeInfo.DrawScale = nil
ULandscapeInfo.Layers = nil
ULandscapeInfo.Proxies = nil
