ULandscapeHeightfieldCollisionComponent = {} ---@type UPrimitiveComponent
ULandscapeHeightfieldCollisionComponent.ComponentLayerInfos = nil
ULandscapeHeightfieldCollisionComponent.SectionBaseX = nil
ULandscapeHeightfieldCollisionComponent.SectionBaseY = nil
ULandscapeHeightfieldCollisionComponent.CollisionSizeQuads = nil
ULandscapeHeightfieldCollisionComponent.CollisionScale = nil
ULandscapeHeightfieldCollisionComponent.SimpleCollisionSizeQuads = nil
ULandscapeHeightfieldCollisionComponent.CollisionQuadFlags = nil
ULandscapeHeightfieldCollisionComponent.HeightfieldGuid = nil
ULandscapeHeightfieldCollisionComponent.CachedLocalBox = nil
ULandscapeHeightfieldCollisionComponent.RenderComponent = nil
ULandscapeHeightfieldCollisionComponent.CookedPhysicalMaterials = nil
function ULandscapeHeightfieldCollisionComponent.GetRenderComponent() end
