ULevelStreaming = {} ---@type UObject
ULevelStreaming.PackageName_DEPRECATED = nil
ULevelStreaming.WorldAsset = nil
ULevelStreaming.PackageNameToLoad = nil
ULevelStreaming.LODPackageNames = nil
ULevelStreaming.LevelTransform = nil
ULevelStreaming.LevelLODIndex = nil
ULevelStreaming.StreamingPriority = nil
ULevelStreaming.bShouldBeVisibleInEditor = nil
ULevelStreaming.bShouldBeVisible = nil
ULevelStreaming.bShouldBeLoaded = nil
ULevelStreaming.bLocked = nil
ULevelStreaming.bIsStatic = nil
ULevelStreaming.bShouldBlockOnLoad = nil
ULevelStreaming.bShouldBlockOnUnload = nil
ULevelStreaming.bDisableDistanceStreaming = nil
ULevelStreaming.bDrawOnLevelStatusMap = nil
ULevelStreaming.DrawColor_DEPRECATED = nil
ULevelStreaming.LevelColor = nil
ULevelStreaming.EditorStreamingVolumes = nil
ULevelStreaming.MinTimeBetweenVolumeUnloadRequests = nil
ULevelStreaming.Keywords = nil
ULevelStreaming.OnLevelLoaded = nil
ULevelStreaming.OnLevelUnloaded = nil
ULevelStreaming.OnLevelShown = nil
ULevelStreaming.OnLevelHidden = nil
ULevelStreaming.LoadedLevel = nil
ULevelStreaming.PendingUnloadLevel = nil
ULevelStreaming.FolderPath = nil
function ULevelStreaming.SetShouldBeVisible(bInShouldBeVisible) end
function ULevelStreaming.SetShouldBeLoaded(bInShouldBeLoaded) end
function ULevelStreaming.SetLevelLODIndex(LODIndex) end
function ULevelStreaming.SetPriority(NewPriority) end
function ULevelStreaming.GetWorldAssetPackageFName() end
function ULevelStreaming.ShouldBeLoaded() end
function ULevelStreaming.GetLoadedLevel() end
function ULevelStreaming.IsLevelVisible() end
function ULevelStreaming.IsLevelLoaded() end
function ULevelStreaming.IsStreamingStatePending() end
function ULevelStreaming.CreateInstance(UniqueInstanceName) end
function ULevelStreaming.GetLevelScriptActor() end
