ULightComponent = {} ---@type ULightComponentBase
ULightComponent.Temperature = nil
ULightComponent.MaxDrawDistance = nil
ULightComponent.MaxDistanceFadeRange = nil
ULightComponent.bUseTemperature = nil
ULightComponent.ShadowMapChannel_DEPRECATED = nil
ULightComponent.MinRoughness_DEPRECATED = nil
ULightComponent.SpecularScale = nil
ULightComponent.ShadowResolutionScale = nil
ULightComponent.ShadowBias = nil
ULightComponent.ShadowSlopeBias = nil
ULightComponent.ShadowSharpen = nil
ULightComponent.ContactShadowLength = nil
ULightComponent.ContactShadowLengthInWS = nil
ULightComponent.InverseSquaredFalloff_DEPRECATED = nil
ULightComponent.CastTranslucentShadows = nil
ULightComponent.bCastShadowsFromCinematicObjectsOnly = nil
ULightComponent.bAffectDynamicIndirectLighting = nil
ULightComponent.bForceCachedShadowsForMovablePrimitives = nil
ULightComponent.LightingChannels = nil
ULightComponent.LightFunctionMaterial = nil
ULightComponent.LightFunctionScale = nil
ULightComponent.IESTexture = nil
ULightComponent.bUseIESBrightness = nil
ULightComponent.IESBrightnessScale = nil
ULightComponent.LightFunctionFadeDistance = nil
ULightComponent.DisabledBrightness = nil
ULightComponent.bEnableLightShaftBloom = nil
ULightComponent.BloomScale = nil
ULightComponent.BloomThreshold = nil
ULightComponent.BloomMaxBrightness = nil
ULightComponent.BloomTint = nil
ULightComponent.bUseRayTracedDistanceFieldShadows = nil
ULightComponent.RayStartOffsetDepthScale = nil
function ULightComponent.SetIntensity(NewIntensity) end
function ULightComponent.SetIndirectLightingIntensity(NewIntensity) end
function ULightComponent.SetVolumetricScatteringIntensity(NewIntensity) end
function ULightComponent.SetLightColor(NewLightColor) end
function ULightComponent.SetTemperature(NewTemperature) end
function ULightComponent.SetLightFunctionMaterial(NewLightFunctionMaterial) end
function ULightComponent.SetLightFunctionScale(NewLightFunctionScale) end
function ULightComponent.SetLightFunctionFadeDistance(NewLightFunctionFadeDistance) end
function ULightComponent.SetLightFunctionDisabledBrightness(NewValue) end
function ULightComponent.SetAffectDynamicIndirectLighting(bNewValue) end
function ULightComponent.SetAffectTranslucentLighting(bNewValue) end
function ULightComponent.SetTransmission(bNewValue) end
function ULightComponent.SetEnableLightShaftBloom(bNewValue) end
function ULightComponent.SetBloomScale(NewValue) end
function ULightComponent.SetBloomThreshold(NewValue) end
function ULightComponent.SetBloomMaxBrightness(NewValue) end
function ULightComponent.SetBloomTint(NewValue) end
function ULightComponent.SetIESTexture(NewValue) end
function ULightComponent.SetUseIESBrightness(bNewValue) end
function ULightComponent.SetIESBrightnessScale(NewValue) end
function ULightComponent.SetShadowBias(NewValue) end
function ULightComponent.SetShadowSlopeBias(NewValue) end
function ULightComponent.SetSpecularScale(NewValue) end
function ULightComponent.SetForceCachedShadowsForMovablePrimitives(bNewValue) end
