UMaterialExpressionRuntimeVirtualTextureReplace = {} ---@type UMaterialExpression
UMaterialExpressionRuntimeVirtualTextureReplace.Default = nil
UMaterialExpressionRuntimeVirtualTextureReplace.VirtualTextureOutput = nil
