UMaterialExpressionTextureSampleParameter = {} ---@type UMaterialExpressionTextureSample
UMaterialExpressionTextureSampleParameter.ParameterName = nil
UMaterialExpressionTextureSampleParameter.ExpressionGUID = nil
UMaterialExpressionTextureSampleParameter.Group = nil
UMaterialExpressionTextureSampleParameter.SortPriority = nil
UMaterialExpressionTextureSampleParameter.ChannelNames = nil
