UMaterialExpressionSingleLayerWaterMaterialOutput = {} ---@type UMaterialExpressionCustomOutput
UMaterialExpressionSingleLayerWaterMaterialOutput.ScatteringCoefficients = nil
UMaterialExpressionSingleLayerWaterMaterialOutput.AbsorptionCoefficients = nil
UMaterialExpressionSingleLayerWaterMaterialOutput.PhaseG = nil
