UMaterialExpressionRuntimeVirtualTextureSample = {} ---@type UMaterialExpression
UMaterialExpressionRuntimeVirtualTextureSample.Coordinates = nil
UMaterialExpressionRuntimeVirtualTextureSample.MipValue = nil
UMaterialExpressionRuntimeVirtualTextureSample.VirtualTexture = nil
UMaterialExpressionRuntimeVirtualTextureSample.MaterialType = nil
UMaterialExpressionRuntimeVirtualTextureSample.bSinglePhysicalSpace = nil
UMaterialExpressionRuntimeVirtualTextureSample.MipValueMode = nil
UMaterialExpressionRuntimeVirtualTextureSample.RVTMVM_None = nil
