UMaterialExpressionLandscapeLayerCoords = {} ---@type UMaterialExpression
UMaterialExpressionLandscapeLayerCoords.MappingType = nil
UMaterialExpressionLandscapeLayerCoords.CustomUVType = nil
UMaterialExpressionLandscapeLayerCoords.MappingScale = nil
UMaterialExpressionLandscapeLayerCoords.MappingRotation = nil
UMaterialExpressionLandscapeLayerCoords.MappingPanU = nil
UMaterialExpressionLandscapeLayerCoords.MappingPanV = nil
