UMaterialExpressionFunctionInput = {} ---@type UMaterialExpression
UMaterialExpressionFunctionInput.Preview = nil
UMaterialExpressionFunctionInput.InputName = nil
UMaterialExpressionFunctionInput.Description = nil
UMaterialExpressionFunctionInput.Id = nil
UMaterialExpressionFunctionInput.InputType = nil
UMaterialExpressionFunctionInput.PreviewValue = nil
UMaterialExpressionFunctionInput.bUsePreviewValueAsDefault = nil
UMaterialExpressionFunctionInput.SortPriority = nil
UMaterialExpressionFunctionInput.bCompilingFunctionPreview = nil
