UMaterialExpressionRuntimeVirtualTextureSampleParameter = {} ---@type UMaterialExpressionRuntimeVirtualTextureSample
UMaterialExpressionRuntimeVirtualTextureSampleParameter.ParameterName = nil
UMaterialExpressionRuntimeVirtualTextureSampleParameter.ExpressionGUID = nil
UMaterialExpressionRuntimeVirtualTextureSampleParameter.Group = nil
UMaterialExpressionRuntimeVirtualTextureSampleParameter.SortPriority = nil
