UMeshVertexPainterKismetLibrary = {} ---@type UBlueprintFunctionLibrary
function UMeshVertexPainterKismetLibrary.PaintVerticesSingleColor(StaticMeshComponent, FillColor) end
function UMeshVertexPainterKismetLibrary.PaintVerticesLerpAlongAxis(StaticMeshComponent, StartColor, EndColor, Axis) end
function UMeshVertexPainterKismetLibrary.RemovePaintedVertices(StaticMeshComponent) end
