UMotionTrackedDeviceFunctionLibrary = {} ---@type UBlueprintFunctionLibrary
function UMotionTrackedDeviceFunctionLibrary.IsMotionTrackedDeviceCountManagementNecessary() end
function UMotionTrackedDeviceFunctionLibrary.SetIsControllerMotionTrackingEnabledByDefault(Enable) end
function UMotionTrackedDeviceFunctionLibrary.GetMaximumMotionTrackedControllerCount() end
function UMotionTrackedDeviceFunctionLibrary.GetMotionTrackingEnabledControllerCount() end
function UMotionTrackedDeviceFunctionLibrary.IsMotionTrackingEnabledForDevice(PlayerIndex, Hand) end
function UMotionTrackedDeviceFunctionLibrary.IsMotionTrackingEnabledForSource(PlayerIndex, SourceName) end
function UMotionTrackedDeviceFunctionLibrary.IsMotionTrackingEnabledForComponent(MotionControllerComponent) end
function UMotionTrackedDeviceFunctionLibrary.EnableMotionTrackingOfDevice(PlayerIndex, Hand) end
function UMotionTrackedDeviceFunctionLibrary.EnableMotionTrackingOfSource(PlayerIndex, SourceName) end
function UMotionTrackedDeviceFunctionLibrary.EnableMotionTrackingForComponent(MotionControllerComponent) end
function UMotionTrackedDeviceFunctionLibrary.DisableMotionTrackingOfDevice(PlayerIndex, Hand) end
function UMotionTrackedDeviceFunctionLibrary.DisableMotionTrackingOfSource(PlayerIndex, SourceName) end
function UMotionTrackedDeviceFunctionLibrary.DisableMotionTrackingForComponent(MotionControllerComponent) end
function UMotionTrackedDeviceFunctionLibrary.DisableMotionTrackingOfAllControllers() end
function UMotionTrackedDeviceFunctionLibrary.DisableMotionTrackingOfControllersForPlayer(PlayerIndex) end
function UMotionTrackedDeviceFunctionLibrary.EnumerateMotionSources() end
function UMotionTrackedDeviceFunctionLibrary.GetActiveTrackingSystemName() end
function UMotionTrackedDeviceFunctionLibrary.IsMotionSourceTracking(PlayerIndex, SourceName) end
