UMovieScene3DAttachSection = {} ---@type UMovieScene3DConstraintSection
UMovieScene3DAttachSection.AttachSocketName = nil
UMovieScene3DAttachSection.AttachComponentName = nil
UMovieScene3DAttachSection.bFullRevertOnDetach = nil
UMovieScene3DAttachSection.ReAttachOnDetach = nil
UMovieScene3DAttachSection.AttachmentLocationRule = nil
UMovieScene3DAttachSection.AttachmentRotationRule = nil
UMovieScene3DAttachSection.AttachmentScaleRule = nil
UMovieScene3DAttachSection.DetachmentLocationRule = nil
UMovieScene3DAttachSection.DetachmentRotationRule = nil
UMovieScene3DAttachSection.DetachmentScaleRule = nil
