UNavAreaMeta_SwitchByAgent = {} ---@type UNavAreaMeta
UNavAreaMeta_SwitchByAgent.Agent0Area = nil
UNavAreaMeta_SwitchByAgent.Agent1Area = nil
UNavAreaMeta_SwitchByAgent.Agent2Area = nil
UNavAreaMeta_SwitchByAgent.Agent3Area = nil
UNavAreaMeta_SwitchByAgent.Agent4Area = nil
UNavAreaMeta_SwitchByAgent.Agent5Area = nil
UNavAreaMeta_SwitchByAgent.Agent6Area = nil
UNavAreaMeta_SwitchByAgent.Agent7Area = nil
UNavAreaMeta_SwitchByAgent.Agent8Area = nil
UNavAreaMeta_SwitchByAgent.Agent9Area = nil
UNavAreaMeta_SwitchByAgent.Agent10Area = nil
UNavAreaMeta_SwitchByAgent.Agent11Area = nil
UNavAreaMeta_SwitchByAgent.Agent12Area = nil
UNavAreaMeta_SwitchByAgent.Agent13Area = nil
UNavAreaMeta_SwitchByAgent.Agent14Area = nil
UNavAreaMeta_SwitchByAgent.Agent15Area = nil
