UNavLinkCustomComponent = {} ---@type UNavRelevantComponent
UNavLinkCustomComponent.NavLinkUserId = nil
UNavLinkCustomComponent.EnabledAreaClass = nil
UNavLinkCustomComponent.DisabledAreaClass = nil
UNavLinkCustomComponent.SupportedAgents = nil
UNavLinkCustomComponent.LinkRelativeStart = nil
UNavLinkCustomComponent.LinkRelativeEnd = nil
UNavLinkCustomComponent.LinkDirection = nil
UNavLinkCustomComponent.bLinkEnabled = nil
UNavLinkCustomComponent.bNotifyWhenEnabled = nil
UNavLinkCustomComponent.bNotifyWhenDisabled = nil
UNavLinkCustomComponent.bCreateBoxObstacle = nil
UNavLinkCustomComponent.ObstacleOffset = nil
UNavLinkCustomComponent.ObstacleExtent = nil
UNavLinkCustomComponent.ObstacleAreaClass = nil
UNavLinkCustomComponent.BroadcastRadius = nil
UNavLinkCustomComponent.BroadcastInterval = nil
UNavLinkCustomComponent.BroadcastChannel = nil
