UParticleModuleBeamTarget = {} ---@type UParticleModuleBeamBase
UParticleModuleBeamTarget.TargetMethod = nil
UParticleModuleBeamTarget.TargetName = nil
UParticleModuleBeamTarget.Target = nil
UParticleModuleBeamTarget.bTargetAbsolute = nil
UParticleModuleBeamTarget.bLockTarget = nil
UParticleModuleBeamTarget.TargetTangentMethod = nil
UParticleModuleBeamTarget.TargetTangent = nil
UParticleModuleBeamTarget.bLockTargetTangent = nil
UParticleModuleBeamTarget.TargetStrength = nil
UParticleModuleBeamTarget.bLockTargetStength = nil
UParticleModuleBeamTarget.LockRadius = nil
