UParticleModuleCollision = {} ---@type UParticleModuleCollisionBase
UParticleModuleCollision.DampingFactor = nil
UParticleModuleCollision.DampingFactorRotation = nil
UParticleModuleCollision.MaxCollisions = nil
UParticleModuleCollision.CollisionCompletionOption = nil
UParticleModuleCollision.CollisionTypes = nil
UParticleModuleCollision.bApplyPhysics = nil
UParticleModuleCollision.bIgnoreTriggerVolumes = nil
UParticleModuleCollision.ParticleMass = nil
UParticleModuleCollision.DirScalar = nil
UParticleModuleCollision.bPawnsDoNotDecrementCount = nil
UParticleModuleCollision.bOnlyVerticalNormalsDecrementCount = nil
UParticleModuleCollision.VerticalFudgeFactor = nil
UParticleModuleCollision.DelayAmount = nil
UParticleModuleCollision.bDropDetail = nil
UParticleModuleCollision.bCollideOnlyIfVisible = nil
UParticleModuleCollision.bIgnoreSourceActor = nil
UParticleModuleCollision.MaxCollisionDistance = nil
