UParticleModuleEventReceiverSpawn = {} ---@type UParticleModuleEventReceiverBase
UParticleModuleEventReceiverSpawn.SpawnCount = nil
UParticleModuleEventReceiverSpawn.bUseParticleTime = nil
UParticleModuleEventReceiverSpawn.bUsePSysLocation = nil
UParticleModuleEventReceiverSpawn.bInheritVelocity = nil
UParticleModuleEventReceiverSpawn.InheritVelocityScale = nil
UParticleModuleEventReceiverSpawn.PhysicalMaterials = nil
UParticleModuleEventReceiverSpawn.bBanPhysicalMaterials = nil
