UParticleModuleVectorFieldGlobal = {} ---@type UParticleModuleVectorFieldBase
UParticleModuleVectorFieldGlobal.bOverrideGlobalVectorFieldTightness = nil
UParticleModuleVectorFieldGlobal.GlobalVectorFieldScale = nil
UParticleModuleVectorFieldGlobal.GlobalVectorFieldTightness = nil
