UParticleModuleAccelerationDragScaleOverLife = {} ---@type UParticleModuleAccelerationBase
UParticleModuleAccelerationDragScaleOverLife.DragScale_DEPRECATED = nil
UParticleModuleAccelerationDragScaleOverLife.DragScaleRaw = nil
