UParticleModuleVectorFieldScaleOverLife = {} ---@type UParticleModuleVectorFieldBase
UParticleModuleVectorFieldScaleOverLife.VectorFieldScaleOverLife_DEPRECATED = nil
UParticleModuleVectorFieldScaleOverLife.VectorFieldScaleOverLifeRaw = nil
