UParticleModuleAttractorPoint = {} ---@type UParticleModuleAttractorBase
UParticleModuleAttractorPoint.Position = nil
UParticleModuleAttractorPoint.Range = nil
UParticleModuleAttractorPoint.Strength = nil
UParticleModuleAttractorPoint.StrengthByDistance = nil
UParticleModuleAttractorPoint.bAffectBaseVelocity = nil
UParticleModuleAttractorPoint.bOverrideVelocity = nil
UParticleModuleAttractorPoint.bUseWorldSpacePosition = nil
UParticleModuleAttractorPoint.Positive_X = nil
UParticleModuleAttractorPoint.Positive_Y = nil
UParticleModuleAttractorPoint.Positive_Z = nil
UParticleModuleAttractorPoint.Negative_X = nil
UParticleModuleAttractorPoint.Negative_Y = nil
UParticleModuleAttractorPoint.Negative_Z = nil
