UPlanePositionGizmo = {} ---@type UInteractiveGizmo
UPlanePositionGizmo.AxisSource = nil
UPlanePositionGizmo.ParameterSource = nil
UPlanePositionGizmo.HitTarget = nil
UPlanePositionGizmo.StateTarget = nil
UPlanePositionGizmo.bInInteraction = nil
UPlanePositionGizmo.InteractionOrigin = nil
UPlanePositionGizmo.InteractionNormal = nil
UPlanePositionGizmo.InteractionAxisX = nil
UPlanePositionGizmo.InteractionAxisY = nil
UPlanePositionGizmo.InteractionStartPoint = nil
UPlanePositionGizmo.InteractionCurPoint = nil
UPlanePositionGizmo.InteractionStartParameter = nil
UPlanePositionGizmo.InteractionCurParameter = nil
