UScrollBox = {} ---@type UPanelWidget
UScrollBox.WidgetStyle = nil
UScrollBox.WidgetBarStyle = nil
UScrollBox.Style_DEPRECATED = nil
UScrollBox.BarStyle_DEPRECATED = nil
UScrollBox.Orientation = nil
UScrollBox.ScrollBarVisibility = nil
UScrollBox.ConsumeMouseWheel = nil
UScrollBox.ScrollbarThickness = nil
UScrollBox.ScrollbarPadding = nil
UScrollBox.AlwaysShowScrollbar = nil
UScrollBox.AlwaysShowScrollbarTrack = nil
UScrollBox.AllowOverscroll = nil
UScrollBox.bAnimateWheelScrolling = nil
UScrollBox.NavigationDestination = nil
UScrollBox.NavigationScrollPadding = nil
UScrollBox.bAllowRightClickDragScrolling = nil
UScrollBox.WheelScrollMultiplier = nil
UScrollBox.OnUserScrolled = nil
function UScrollBox.SetConsumeMouseWheel(NewConsumeMouseWheel) end
function UScrollBox.SetOrientation(NewOrientation) end
function UScrollBox.SetScrollBarVisibility(NewScrollBarVisibility) end
function UScrollBox.SetScrollbarThickness(NewScrollbarThickness) end
function UScrollBox.SetScrollbarPadding(NewScrollbarPadding) end
function UScrollBox.SetAlwaysShowScrollbar(NewAlwaysShowScrollbar) end
function UScrollBox.SetAllowOverscroll(NewAllowOverscroll) end
function UScrollBox.SetAnimateWheelScrolling(bShouldAnimateWheelScrolling) end
function UScrollBox.SetWheelScrollMultiplier(NewWheelScrollMultiplier) end
function UScrollBox.EndInertialScrolling() end
function UScrollBox.SetScrollOffset(NewScrollOffset) end
function UScrollBox.GetScrollOffset() end
function UScrollBox.GetScrollOffsetOfEnd() end
function UScrollBox.GetViewOffsetFraction() end
function UScrollBox.ScrollToStart() end
function UScrollBox.ScrollToEnd() end
function UScrollBox.ScrollWidgetIntoView(WidgetToFind) end
