USizeBox = {} ---@type UContentWidget
USizeBox.WidthOverride = nil
USizeBox.HeightOverride = nil
USizeBox.MinDesiredWidth = nil
USizeBox.MinDesiredHeight = nil
USizeBox.MaxDesiredWidth = nil
USizeBox.MaxDesiredHeight = nil
USizeBox.MinAspectRatio = nil
USizeBox.MaxAspectRatio = nil
USizeBox.bOverride_WidthOverride = nil
USizeBox.bOverride_HeightOverride = nil
USizeBox.bOverride_MinDesiredWidth = nil
USizeBox.bOverride_MinDesiredHeight = nil
USizeBox.bOverride_MaxDesiredWidth = nil
USizeBox.bOverride_MaxDesiredHeight = nil
USizeBox.bOverride_MinAspectRatio = nil
USizeBox.bOverride_MaxAspectRatio = nil
function USizeBox.SetWidthOverride(InWidthOverride) end
function USizeBox.ClearWidthOverride() end
function USizeBox.SetHeightOverride(InHeightOverride) end
function USizeBox.ClearHeightOverride() end
function USizeBox.SetMinDesiredWidth(InMinDesiredWidth) end
function USizeBox.ClearMinDesiredWidth() end
function USizeBox.SetMinDesiredHeight(InMinDesiredHeight) end
function USizeBox.ClearMinDesiredHeight() end
function USizeBox.SetMaxDesiredWidth(InMaxDesiredWidth) end
function USizeBox.ClearMaxDesiredWidth() end
function USizeBox.SetMaxDesiredHeight(InMaxDesiredHeight) end
function USizeBox.ClearMaxDesiredHeight() end
function USizeBox.SetMinAspectRatio(InMinAspectRatio) end
function USizeBox.SetMaxAspectRatio(InMaxAspectRatio) end
function USizeBox.ClearMinAspectRatio() end
function USizeBox.ClearMaxAspectRatio() end
