USlider = {} ---@type UWidget
USlider.Value = nil
USlider.ValueDelegate = nil
USlider.MinValue = nil
USlider.MaxValue = nil
USlider.WidgetStyle = nil
USlider.Orientation = nil
USlider.SliderBarColor = nil
USlider.SliderHandleColor = nil
USlider.IndentHandle = nil
USlider.Locked = nil
USlider.MouseUsesStep = nil
USlider.RequiresControllerLock = nil
USlider.StepSize = nil
USlider.IsFocusable = nil
USlider.OnMouseCaptureBegin = nil
USlider.OnMouseCaptureEnd = nil
USlider.OnControllerCaptureBegin = nil
USlider.OnControllerCaptureEnd = nil
USlider.OnValueChanged = nil
function USlider.GetValue() end
function USlider.GetNormalizedValue() end
function USlider.SetValue(InValue) end
function USlider.SetMinValue(InValue) end
function USlider.SetMaxValue(InValue) end
function USlider.SetIndentHandle(InValue) end
function USlider.SetLocked(InValue) end
function USlider.SetStepSize(InValue) end
function USlider.SetSliderBarColor(InValue) end
function USlider.SetSliderHandleColor(InValue) end
