USoundCue = {} ---@type USoundBase
USoundCue.bPrimeOnLoad = nil
USoundCue.FirstNode = nil
USoundCue.VolumeMultiplier = nil
USoundCue.PitchMultiplier = nil
USoundCue.AttenuationOverrides = nil
USoundCue.AllNodes = nil
USoundCue.SoundCueGraph = nil
USoundCue.SubtitlePriority = nil
USoundCue.bOverrideAttenuation = nil
USoundCue.bExcludeFromRandomNodeBranchCulling = nil
USoundCue.bHasPlayWhenSilent = nil
