USpinBox = {} ---@type UWidget
USpinBox.Value = nil
USpinBox.ValueDelegate = nil
USpinBox.WidgetStyle = nil
USpinBox.Style_DEPRECATED = nil
USpinBox.Delta = nil
USpinBox.SliderExponent = nil
USpinBox.Font = nil
USpinBox.Justification = nil
USpinBox.MinDesiredWidth = nil
USpinBox.ClearKeyboardFocusOnCommit = nil
USpinBox.SelectAllTextOnCommit = nil
USpinBox.ForegroundColor = nil
USpinBox.OnValueChanged = nil
USpinBox.OnValueCommitted = nil
USpinBox.OnBeginSliderMovement = nil
USpinBox.OnEndSliderMovement = nil
USpinBox.bOverride_MinValue = nil
USpinBox.bOverride_MaxValue = nil
USpinBox.bOverride_MinSliderValue = nil
USpinBox.bOverride_MaxSliderValue = nil
USpinBox.MinValue = nil
USpinBox.MaxValue = nil
USpinBox.MinSliderValue = nil
USpinBox.MaxSliderValue = nil
function USpinBox.GetValue() end
function USpinBox.SetValue(NewValue) end
function USpinBox.GetMinValue() end
function USpinBox.SetMinValue(NewValue) end
function USpinBox.ClearMinValue() end
function USpinBox.GetMaxValue() end
function USpinBox.SetMaxValue(NewValue) end
function USpinBox.ClearMaxValue() end
function USpinBox.GetMinSliderValue() end
function USpinBox.SetMinSliderValue(NewValue) end
function USpinBox.ClearMinSliderValue() end
function USpinBox.GetMaxSliderValue() end
function USpinBox.SetMaxSliderValue(NewValue) end
function USpinBox.ClearMaxSliderValue() end
function USpinBox.SetForegroundColor(InForegroundColor) end
