UStaticMeshComponent = {} ---@type UMeshComponent
UStaticMeshComponent.ForcedLodModel = nil
UStaticMeshComponent.PreviousLODLevel = nil
UStaticMeshComponent.MinLOD = nil
UStaticMeshComponent.SubDivisionStepSize = nil
UStaticMeshComponent.StaticMesh = nil
UStaticMeshComponent.WireframeColorOverride = nil
UStaticMeshComponent.bEvaluateWorldPositionOffset = nil
UStaticMeshComponent.SelectedEditorSection = nil
UStaticMeshComponent.SelectedEditorMaterial = nil
UStaticMeshComponent.SectionIndexPreview = nil
UStaticMeshComponent.MaterialIndexPreview = nil
UStaticMeshComponent.StaticMeshImportVersion = nil
UStaticMeshComponent.bOverrideWireframeColor = nil
UStaticMeshComponent.bOverrideMinLOD = nil
UStaticMeshComponent.bOverrideNavigationExport = nil
UStaticMeshComponent.bForceNavigationObstacle = nil
UStaticMeshComponent.bDisallowMeshPaintPerInstance = nil
UStaticMeshComponent.bIgnoreInstanceForTextureStreaming = nil
UStaticMeshComponent.bOverrideLightMapRes = nil
UStaticMeshComponent.bCastDistanceFieldIndirectShadow = nil
UStaticMeshComponent.bOverrideDistanceFieldSelfShadowBias = nil
UStaticMeshComponent.bUseSubDivisions = nil
UStaticMeshComponent.bUseDefaultCollision = nil
UStaticMeshComponent.bCustomOverrideVertexColorPerLOD = nil
UStaticMeshComponent.bDisplayVertexColors = nil
UStaticMeshComponent.bReverseCulling = nil
UStaticMeshComponent.OverriddenLightMapRes = nil
UStaticMeshComponent.DistanceFieldIndirectShadowMinVisibility = nil
UStaticMeshComponent.DistanceFieldSelfShadowBias = nil
UStaticMeshComponent.StreamingDistanceMultiplier = nil
UStaticMeshComponent.IrrelevantLights_DEPRECATED = nil
UStaticMeshComponent.LODData = nil
UStaticMeshComponent.StreamingTextureData = nil
UStaticMeshComponent.StaticMeshDerivedDataKey = nil
UStaticMeshComponent.MaterialStreamingRelativeBoxes = nil
UStaticMeshComponent.LightmassSettings = nil
function UStaticMeshComponent.OnRep_StaticMesh(OldStaticMesh) end
function UStaticMeshComponent.SetStaticMesh(NewMesh) end
function UStaticMeshComponent.SetForcedLodModel(NewForcedLodModel) end
function UStaticMeshComponent.SetDistanceFieldSelfShadowBias(NewValue) end
function UStaticMeshComponent.GetLocalBounds(Min, Max) end
function UStaticMeshComponent.SetReverseCulling(ReverseCulling) end
