UStaticMesh = {} ---@type UStreamableRenderAsset
UStaticMesh.SourceModels = nil
UStaticMesh.SectionInfoMap = nil
UStaticMesh.OriginalSectionInfoMap = nil
UStaticMesh.LODGroup = nil
UStaticMesh.NumStreamedLODs = nil
UStaticMesh.ImportVersion = nil
UStaticMesh.MaterialRemapIndexPerImportVersion = nil
UStaticMesh.LightmapUVVersion = nil
UStaticMesh.bAutoComputeLODScreenSize = nil
UStaticMesh.Materials_DEPRECATED = nil
UStaticMesh.MinLOD = nil
UStaticMesh.LpvBiasMultiplier = nil
UStaticMesh.StaticMaterials = nil
UStaticMesh.LightmapUVDensity = nil
UStaticMesh.LightMapResolution = nil
UStaticMesh.LightMapCoordinateIndex = nil
UStaticMesh.DistanceFieldSelfShadowBias = nil
UStaticMesh.BodySetup = nil
UStaticMesh.LODForCollision = nil
UStaticMesh.bGenerateMeshDistanceField = nil
UStaticMesh.bStripComplexCollisionForConsole_DEPRECATED = nil
UStaticMesh.bHasNavigationData = nil
UStaticMesh.bSupportUniformlyDistributedSampling = nil
UStaticMesh.bIsBuiltAtRuntime = nil
UStaticMesh.bAllowCPUAccess = nil
UStaticMesh.bSupportGpuUniformlyDistributedSampling = nil
UStaticMesh.AssetImportData = nil
UStaticMesh.SourceFilePath_DEPRECATED = nil
UStaticMesh.SourceFileTimestamp_DEPRECATED = nil
UStaticMesh.ThumbnailInfo = nil
UStaticMesh.EditorCameraPosition = nil
UStaticMesh.bCustomizedCollision = nil
UStaticMesh.LODForOccluderMesh = nil
UStaticMesh.Sockets = nil
UStaticMesh.PositiveBoundsExtension = nil
UStaticMesh.NegativeBoundsExtension = nil
UStaticMesh.ExtendedBounds = nil
UStaticMesh.ElementToIgnoreForTexFactor = nil
UStaticMesh.AssetUserData = nil
UStaticMesh.EditableMesh = nil
UStaticMesh.ComplexCollisionMesh = nil
UStaticMesh.NavCollision = nil
function UStaticMesh.GetMinimumLODForPlatforms(PlatformMinimumLODs) end
function UStaticMesh.GetMinimumLODForPlatform(PlatformName) end
function UStaticMesh.CreateStaticMeshDescription() end
function UStaticMesh.BuildFromStaticMeshDescriptions(StaticMeshDescriptions) end
function UStaticMesh.SetNumSourceModels(Num) end
function UStaticMesh.GetNumLODs() end
function  end
function UStaticMesh.GetBoundingBox() end
function UStaticMesh.GetNumSections(InLOD) end
function UStaticMesh.GetMaterial(MaterialIndex) end
function UStaticMesh.AddMaterial(Material) end
function UStaticMesh.GetMaterialIndex(MaterialSlotName) end
function UStaticMesh.AddSocket(Socket) end
function  end
function UStaticMesh.RemoveSocket(Socket) end
function UStaticMesh.SetMaterial(MaterialIndex, NewMaterial) end
