UStreamableRenderAsset = {} ---@type UObject
UStreamableRenderAsset.ForceMipLevelsToBeResidentTimestamp = nil
UStreamableRenderAsset.NumCinematicMipLevels = nil
UStreamableRenderAsset.StreamingIndex = nil
UStreamableRenderAsset.CachedCombinedLODBias = nil
UStreamableRenderAsset.CachedNumResidentLODs = nil
UStreamableRenderAsset.bCachedReadyForStreaming = nil
UStreamableRenderAsset.NeverStream = nil
UStreamableRenderAsset.bGlobalForceMipLevelsToBeResident = nil
UStreamableRenderAsset.bIsStreamable = nil
UStreamableRenderAsset.bHasStreamingUpdatePending = nil
UStreamableRenderAsset.bForceMiplevelsToBeResident = nil
UStreamableRenderAsset.bIgnoreStreamingMipBias = nil
UStreamableRenderAsset.bUseCinematicMipLevels = nil
