UTextRenderComponent = {} ---@type UPrimitiveComponent
UTextRenderComponent.Text = nil
UTextRenderComponent.TextMaterial = nil
UTextRenderComponent.Font = nil
UTextRenderComponent.HorizontalAlignment = nil
UTextRenderComponent.VerticalAlignment = nil
UTextRenderComponent.TextRenderColor = nil
UTextRenderComponent.XScale = nil
UTextRenderComponent.YScale = nil
UTextRenderComponent.WorldSize = nil
UTextRenderComponent.InvDefaultSize = nil
UTextRenderComponent.HorizSpacingAdjust = nil
UTextRenderComponent.VertSpacingAdjust = nil
UTextRenderComponent.bAlwaysRenderAsText = nil
function UTextRenderComponent.SetText(Value) end
function UTextRenderComponent.K2_SetText(Value) end
function UTextRenderComponent.SetTextMaterial(Material) end
function UTextRenderComponent.SetFont(Value) end
function UTextRenderComponent.SetHorizontalAlignment(Value) end
function UTextRenderComponent.SetVerticalAlignment(Value) end
function UTextRenderComponent.SetTextRenderColor(Value) end
function UTextRenderComponent.SetXScale(Value) end
function UTextRenderComponent.SetYScale(Value) end
function UTextRenderComponent.SetHorizSpacingAdjust(Value) end
function UTextRenderComponent.SetVertSpacingAdjust(Value) end
function UTextRenderComponent.SetWorldSize(Value) end
function UTextRenderComponent.GetTextLocalSize() end
function UTextRenderComponent.GetTextWorldSize() end
