UVectorFieldAnimated = {} ---@type UVectorField
UVectorFieldAnimated.Texture = nil
UVectorFieldAnimated.ConstructionOp = nil
UVectorFieldAnimated.VolumeSizeX = nil
UVectorFieldAnimated.VolumeSizeY = nil
UVectorFieldAnimated.VolumeSizeZ = nil
UVectorFieldAnimated.SubImagesX = nil
UVectorFieldAnimated.SubImagesY = nil
UVectorFieldAnimated.FrameCount = nil
UVectorFieldAnimated.FramesPerSecond = nil
UVectorFieldAnimated.bLoop = nil
UVectorFieldAnimated.NoiseField = nil
UVectorFieldAnimated.NoiseScale = nil
UVectorFieldAnimated.NoiseMax = nil
