UWidgetComponent = {} ---@type UMeshComponent
UWidgetComponent.Space = nil
UWidgetComponent.TimingPolicy = nil
UWidgetComponent.WidgetClass = nil
UWidgetComponent.DrawSize = nil
UWidgetComponent.bManuallyRedraw = nil
UWidgetComponent.bRedrawRequested = nil
UWidgetComponent.RedrawTime = nil
UWidgetComponent.CurrentDrawSize = nil
UWidgetComponent.bDrawAtDesiredSize = nil
UWidgetComponent.Pivot = nil
UWidgetComponent.bReceiveHardwareInput = nil
UWidgetComponent.bWindowFocusable = nil
UWidgetComponent.WindowVisibility = nil
UWidgetComponent.bApplyGammaCorrection = nil
UWidgetComponent.OwnerPlayer = nil
UWidgetComponent.BackgroundColor = nil
UWidgetComponent.TintColorAndOpacity = nil
UWidgetComponent.OpacityFromTexture = nil
UWidgetComponent.BlendMode = nil
UWidgetComponent.bIsTwoSided = nil
UWidgetComponent.TickWhenOffscreen = nil
UWidgetComponent.Widget = nil
UWidgetComponent.BodySetup = nil
UWidgetComponent.TranslucentMaterial = nil
UWidgetComponent.TranslucentMaterial_OneSided = nil
UWidgetComponent.OpaqueMaterial = nil
UWidgetComponent.OpaqueMaterial_OneSided = nil
UWidgetComponent.MaskedMaterial = nil
UWidgetComponent.MaskedMaterial_OneSided = nil
UWidgetComponent.RenderTarget = nil
UWidgetComponent.MaterialInstance = nil
UWidgetComponent.bAddedToScreen = nil
UWidgetComponent.bEditTimeUsable = nil
UWidgetComponent.SharedLayerName = nil
UWidgetComponent.LayerZOrder = nil
UWidgetComponent.GeometryMode = nil
UWidgetComponent.CylinderArcAngle = nil
function UWidgetComponent.GetUserWidgetObject() end
function UWidgetComponent.GetRenderTarget() end
function UWidgetComponent.GetMaterialInstance() end
function UWidgetComponent.SetWidget(Widget) end
function UWidgetComponent.SetOwnerPlayer(LocalPlayer) end
function UWidgetComponent.GetManuallyRedraw() end
function UWidgetComponent.SetManuallyRedraw(bUseManualRedraw) end
function UWidgetComponent.GetOwnerPlayer() end
function UWidgetComponent.GetDrawSize() end
function UWidgetComponent.GetCurrentDrawSize() end
function UWidgetComponent.SetDrawSize(Size) end
function UWidgetComponent.RequestRedraw() end
function UWidgetComponent.GetTwoSided() end
function UWidgetComponent.SetTwoSided(bWantTwoSided) end
function UWidgetComponent.GetTickWhenOffscreen() end
function UWidgetComponent.SetTickWhenOffscreen(bWantTickWhenOffscreen) end
function UWidgetComponent.SetBackgroundColor(NewBackgroundColor) end
function UWidgetComponent.SetTintColorAndOpacity(NewTintColorAndOpacity) end
function UWidgetComponent.GetPivot() end
function UWidgetComponent.SetPivot(InPivot) end
function UWidgetComponent.GetDrawAtDesiredSize() end
function UWidgetComponent.SetDrawAtDesiredSize(bInDrawAtDesiredSize) end
function UWidgetComponent.GetRedrawTime() end
function UWidgetComponent.SetRedrawTime(InRedrawTime) end
function UWidgetComponent.GetWidgetSpace() end
function UWidgetComponent.SetWidgetSpace(NewSpace) end
function UWidgetComponent.GetGeometryMode() end
function UWidgetComponent.SetGeometryMode(InGeometryMode) end
function UWidgetComponent.GetCylinderArcAngle() end
function UWidgetComponent.SetCylinderArcAngle(InCylinderArcAngle) end
function UWidgetComponent.GetWindowFocusable() end
function UWidgetComponent.SetWindowFocusable(bInWindowFocusable) end
function UWidgetComponent.GetWindowVisiblility() end
function UWidgetComponent.SetWindowVisibility(InVisibility) end
